keys:
#  - &yubikey age1yubikey1.......  # Hier deinen YubiKey Public Key eintragen
  - &laptop  age15uthmkd6u2fgfvy28p4nl9pm42hw5rp2aa7sqa9yynx9cajrrdtsdh25u7
creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
#        - *yubikey
        - *laptop
