#monitor = Virtual-1, 1920x1080@60, 0x0, 1
monitor = DP-1, 3840x2160@60, 0x0, 1.5
monitor = DP-3, 3840x2160@60, 2560x0, 1.5
input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0
}

general {
    layout = dwindle
}

# noctalia-shell wird unter Fedora via qs -c aufgerufen
exec-once = qs -c noctalia-shell

exec-once = hyprctl setcursor Breeze_cursor 24
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Breeze_cursors
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Breeze_cursors

bind = $mainMod, B, exec, ~/.local/bin/zen
bind = $mainMod, SPACE, exec, qs -c noctalia-shell ipc call launcher toggle
bind = $mainMod, L, exec, qs -c noctalia-shell ipc call lockScreen lock
bind = $mainMod SHIFT, W, exec, qs -c noctalia-shell ipc call wallpaper toggle
bind = $mainMod SHIFT, T, exec, qs -c noctalia-shell ipc call settings openTab "colorScheme"
bind = CTRLALT, DELETE, exec, qs -c noctalia-shell ipc call sessionMenu toggle
