color0 #121411
color1 #ffb4ab
color2 #8fd88a
color3 #b9ccb3
color4 #a0cfd4
color5 #8fd88a
color6 #b9ccb3
color7 #e2e3dd
color8 #8c9388
color9 #ffb4ab
color10 #8fd88a
color11 #b9ccb3
color12 #a0cfd4
color13 #8fd88a
color14 #b9ccb3
color15 #e2e3dd

cursor                #e2e3dd
cursor_text_color     #121411
background            #121411
foreground            #e2e3dd
selection_foreground  #c2c9bd
selection_background  #424940
active_border_color   #8fd88a
inactive_border_color #424940
url_color             #8fd88a

active_tab_foreground   #00390b
active_tab_background   #8fd88a
inactive_tab_foreground #c2c9bd
inactive_tab_background #424940
cursor_trail_color      #c2c9bd
