color0 #111415
color1 #ffb4ab
color2 #5ed4fc
color3 #b3cad5
color4 #c3c3eb
color5 #5ed4fc
color6 #b3cad5
color7 #e1e3e4
color8 #8a9296
color9 #ffb4ab
color10 #5ed4fc
color11 #b3cad5
color12 #c3c3eb
color13 #5ed4fc
color14 #b3cad5
color15 #e1e3e4

cursor                #e1e3e4
cursor_text_color     #111415
background            #111415
foreground            #e1e3e4
selection_foreground  #bfc8cc
selection_background  #40484c
active_border_color   #5ed4fc
inactive_border_color #40484c
url_color             #5ed4fc

active_tab_foreground   #003544
active_tab_background   #5ed4fc
inactive_tab_foreground #bfc8cc
inactive_tab_background #40484c
cursor_trail_color      #bfc8cc
